### ISSUE TITLE
Custom Categories

### ISSUE THREAD

**Issue by shadowfacts** [NOVA-Team/NOVA-Core#101]
(This issue pertains both to NOVA Core and the NOVA Minecraft wrapper)

When using custom categories, the Minecraft wrapper uses the icon of the first block/item to be registered this with the category . So, in order to have custom category icons, code needs to be arranged in a specific way. This not only makes it more difficult (and unintuitive) to add custom icon, but is bad coding style in general.

I suggest that a renderer/texture/icon field be added to Category. This would be used for MC (and any other games that have icons) but ignored if the game just has text titles.

**Comment by gjgfuj** [comment]
It'd be good to keep the first block/item registered as the default icon, but allow it to be replaced if wanted.

**Comment by calclavia** [comment]
Yes. When I coded Category I kinda slapped it together just so I can see what my blocks look like... Feel free to PR

**Comment by shadowfacts** [comment]
Ok, what should be used. I think A Renderer should be used, but correct me if I'm wrong. Although, if it's a dynamic renderer, that kind of fucks up MC because MC wants an Item(Stack?) to be used for the icon.

**Comment by calclavia** [comment]
Don't code in terms of MC. Code in terms of what's the most logical. There's always a way to hack/wrap it. Category is a nice component to categorize blocks and items. If we can keep it component based, it'll be nice. Think of something you can add to the Category component class...

**Comment by halvors** [comment]
See #113

**Comment by halvors** [comment]
This adds the ability to set an item as the "icon" in an category. I think this needs improvement at a later time, but i'm not sure exactly how we should implement this.

Category in NOVA-Core should have some kind of "Icon" or "Texture", and we should trick MC into displaying that as an actual item in the "Creative Tabs".

**Comment by calclavia** [comment]
@halvors Go implement it in the wrapper (BlockConverter, ItemConverter classes)

**Comment by halvors** [comment]
But what should the Category hold? Will the Icon class be relevant to use here?
