### ISSUE TITLE
Exposing DI and Components and Factories

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#102]
Should we expose some DI features? I think components should use DI instead of a registry. The registry is quite redundant.

The problem right now is that mods have no access to the DI entry point, so they can't access DI features.

Also, if @kubuxu can explain, since DI can provide suppliers, why do we even need dedicated registries? Maybe I don't understand SILK well enough.

There's a problem with components right now, and that is people can add components after a block is instantiated. This should not be allowed. If we make components a DI conductor requirement, it'll enforce this rule.

**Comment by gjgfuj** [comment]
Yeah, I'd like to be able to say, here's a class. Inject anything it
requires.

**Comment by Kubuxu** [comment]
Mods can add their own DI modules by NovaMod annotation.

As I said I have to benchmark Silk to make sure that injecting everything won't be an issue.
If it is I might even go for custom DI system with expanded cacheing. So maybe if you want, go for it.

**Comment by gjgfuj** [comment]
Also, I wouldn't prevent components from being added after a block is instantiated. I would instead block  /certain/ components. Because some components could be good to add after instantiation. But. Eh. Whatever.

**Comment by Kubuxu** [comment]
You can always create guard mechanism which would allow adding components only during construction phase. Just lock it after construction in factory.

**Comment by Kubuxu** [comment]
I am doing something similar in: https://github.com/NOVA-Team/NOVA-Core/blob/47f93b1f104bfbef08e391250d7bb77160e9a80c/src/main/java/nova/core/util/EnumSelector.java

**Comment by calclavia** [comment]
@gjgfuj Components should technically only be added during constructor. Otherwise, your client isn't going to have the same components. That'll be one issue...

**Comment by gjgfuj** [comment]
Ah yes, that can be an issue.

**Comment by RX14** [comment]
I thought one of the main advantages of components was that they could be added or removed at runtime? Or do you just mean that you can make it conditional which components are added at construction.

**Comment by Kubuxu** [comment]
@RX14 Runtime meaning construction phase. It I'd huge advantage in comparison with classes and interfaces.

**Comment by RX14** [comment]
@Kubuxu yeah, that makes sense to me.

**Comment by calclavia** [comment]
Yes. Introducing components added not in runtime will also work with DI. It'll just introduce one level of complexity. Client-server different components?

**Comment by Kubuxu** [comment]
The only problem I see is that there is no simple way to pass additional arguments to block this is why I propose following scheme:
```java
Factory.of(StatefullBlock.class) // Factory of simple block
Factory.of(StatefullBlock.class).withFinalizer((block) -> block.special = 5) // Factory of block with special argument
Factory.of(StatefullBlock.class).withArguments(5, 2, "test") // Same as Factory.of(StatefullBlock.class).withFinalizer((block) -> block.arguments(5, 2, "test"))
```

**Comment by calclavia** [comment]
Yes. Something like that looks nicer than holding a factory reference all the time.

**Comment by calclavia** [comment]
I think being able to access the DI injection point is going to be important. @Kubuxu agree?

**Comment by Kubuxu** [comment]
I have done it in my branch. I am exposing Injector and will expose way to install new modules.

**Comment by calclavia** [comment]
@Kubuxu Problem I ran into. When things like Item, Block etc. implement Storable, they cannot have constructors with arguments. In fact, all items need to implement Storable in order to get synced in inventories (just implemented some inventory things in NOVA). Maybe there's no point of having constructor support for blocks, items and entities since there's no way to deserialize them without having an instance anyway? Instead of using constructors, we use finalizers to modify the fields of the block.

Doing it this way, we sacrifice possibilities in making final fields based on constructor arguments, but we won't have to resort to reflection. Coming to think of it, is it really necessary to have blocks with constructors when we can have a finalizer lambda that modifies the block properties right after it's placed?

**Comment by Kubuxu** [comment]
Unfortunately Java is broken:  https://travis-ci.org/NOVA-Team/NOVA-Core/builds/66916291#L701-L733
Corresponding code: https://github.com/NOVA-Team/NOVA-Core/blob/factory/src/main/java/nova/core/util/Manager.java#L28

**Comment by SoniEx2** [comment]
Inventories should go on the ECS, together with power and everything else.
