### ISSUE TITLE
Client auto-download

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#107]
Just thought this would be a neat feature in the future.

When a client connects to a server, and doesn't have the mods, it will popup asking if they want to auto download them (through the mod's official Maven repository, NOT THROUGH THE SERVER).

Safety concerns?

**Comment by AEnterprise** [comment]
i would say only download from official and thrusted sources but other then that i think it would be neat

**Comment by liach** [comment]
Will this be safe?

**Comment by halvors** [comment]
@calclavia This still need a restart of the game?

**Comment by RX14** [comment]
We have already discussed the security issues of this in length. We will promt the user for download and allow downloading form only the NOVA repository where all jar are signed.

**Comment by calclavia** [comment]
@halvors We could potentially integrate an instant mod re-load hot-swap mechanism, but that'll be difficult. Consider how we are all using dummy blocks/tiles, hotswapping is just switching out the wrapped stuff with new stuff.

**Comment by halvors** [comment]
@calclavia Yeah, that sounds great ;)

I think this is safe enough if we download from trusted sources.

**Comment by liach** [comment]
Now I've got another question, how if there's some issue connecting to Nova maven? Will we be allowed to change download link, or disable it simply

**Comment by RX14** [comment]
If you can't connect to the NOVA maven you will simply have to download the mods manually.

**Comment by RX14** [comment]
This is quite a task because of the GPG requirement

**Comment by Kubuxu** [comment]
Instead of GPG we could use just java'a encryption engine: https://docs.oracle.com/javase/tutorial/security/apisign/

**Comment by RX14** [comment]
but mah pgp

**Comment by loordgek** [comment]
can you use https://github.com/MMCWonko/WonkoTheSane ?

**Comment by RX14** [comment]
How does wonko help?

**Comment by RX14** [comment]
maven is much more suited to this downloading of resources owing to it being simple, wonko is useful because it allows for the complexities of the minecraft ecosystem, but we don't need that! all we're doing is downloading jars.

**Comment by loordgek** [comment]
you need to ask the dev from wonko/multimc how it works

**Comment by RX14** [comment]
I have known and discussed wonko for a while, I am aware of what it is and how it works. What features from it do we need more than simple maven?

**Comment by loordgek** [comment]
but are all the nova mods gonne use maven?

**Comment by RX14** [comment]
I strongly disagree with server -> client downloading, but we need an issue for mods that the user already has downloading their dependent plugins...

**Comment by calclavia** [comment]
@RX14 I think if we do it, we just need to warn the player of every single mod that wants to be downloaded by the player. Only Maven repos can be downloaded.

**Comment by RX14** [comment]
Nah, we should use wonko if we wanted to do it, but I strongly disagree with servers making clients download mods, for the reasons about clicking through dialogs we talked about when discussing lib downloading...
