### ISSUE TITLE
raytracing return wrong block face on block edges

### ISSUE THREAD

**Issue by AEnterprise** [NOVA-Team/NOVA-Core#115]
when using the raytracer it correctly finds the first block but not always the correct side you clicked on, noticed while testing the rotatedRendering

**Comment by calclavia** [comment]
Is this resolved?

**Comment by AEnterprise** [comment]
one sec, gona use my test block and breakpoint to confirm that

**Comment by AEnterprise** [comment]
confirmed, raytracing works fine now
