### ISSUE TITLE
collect all events and put them in the same package

### ISSUE THREAD

**Issue by AEnterprise** [NOVA-Team/NOVA-Core#118]
i think the events should all be in the same package, right now they are hidden away in other classes so it is hard to find if there is already an event for something or not (there are block events in the block class, the orientationChangedEvent is in Orientation, ...)

**Comment by calclavia** [comment]
That depends. Some events have a scope (block events are only executed on blocks), and putting them as subclasses gives them context.

**Comment by AEnterprise** [comment]
true but for contect sub-packages and javadoc can also give the required context

**Comment by gjgfuj** [comment]
It makes much more sense as they are though? Block events would be found in
the block section. Something you could do is add an event subpackage to
block, etc.

**Comment by AEnterprise** [comment]
We'll keep them where they are then

**Comment by Caellian** [comment]
I agree, adding event sub-package would be really convenient for IDE-s, and
I don't really think that it's necessary to put them into the same package.

**Comment by calclavia** [comment]
@Caellian Subpackage may work. But it's also nice to have Block.RightClickEvent, because we also have Item.RightClickEvent. This gives it context.

**Comment by Caellian** [comment]
I agree, actually - it might even make more sense that way. Of course, by
keeping in mind the naming conventions already set by written code.

**Comment by gjgfuj** [comment]
Re: right click event, that's not the best name for it. It should really be
activate event or whatever. Since they can rebind it to whatever.

**Comment by calclavia** [comment]
Right Click event is the better name, because it is called when you right click. "Activate" is ambiguous.

**Comment by anti344** [comment]
You could rebind your right click to left click thats what he meant.

**Comment by gjgfuj** [comment]
Right click ties it to a specific input. It does not mean right click, it
is called when its interacted with.
