### ISSUE TITLE
Add a way to find out whether a player is sneaking or not

### ISSUE THREAD

**Issue by halvors** [NOVA-Team/NOVA-Core#126]
Add a way to find out whether a player is sneaking or not, this should probatly be a plugin?

Any suggestions?

**Comment by gjgfuj** [comment]
Sneaking is a pretty MC specific thingy.

**Comment by RX14** [comment]
Games which don't support sneaking can just have it set to false all the time...

**Comment by gjgfuj** [comment]
oh yeah that's true, in that case it doesn't need to be a plugin at all.
just have something in Entity that determines whether they're sneaking or not.
(entities can sneak even if they're not players.)

**Comment by RX14** [comment]
and a way to see if the game support it, we could have an enum for sneaking, not sneaking and not supported... this could be a generic enum too... or just Optional<Boolean> ?

**Comment by magik6k** [comment]
+1 to `Optional<Boolean>`

**Comment by gjgfuj** [comment]
Optional<Boolean> would be good I think.

**Comment by RX14** [comment]
Ok, we are decided

**Comment by calclavia** [comment]
Just do something like: inputManager.isKeyDown(SHIFT)

**Comment by halvors** [comment]
But then i essentially implement this for all voxel engines...

**Comment by gjgfuj** [comment]
Noooooo.... Don't rely on specific keybindings seriously! There is NO
REASON TO ASSUME THAT. Even in Minecraft.

**Comment by RX14** [comment]
@calclavia that's a horrible IDEA...

**Comment by anti344** [comment]
inputManager.isKeyDown(keybindManager.sneakKey) - is a bit better, but still horrible =/

**Comment by gjgfuj** [comment]
Why test for if the sneak key is pressed as opposed to actually seeing if
the player is sneaking..... Plus that'd work on both sides.

**Comment by Victorious3** [comment]
Say, what would this be used for? I only see sneaking being used as a key bind for giving additional interaction methods, but never with "sneaking" in mind.

**Comment by calclavia** [comment]
Because it's a more general implementation. Not all games have sneak, but all keyboards have shift.

**Comment by RX14** [comment]
you can change the keybinds...

**Comment by Victorious3** [comment]
@RX14 And what? I would make it a key binding as well, why would there be an extra "sneaking" flag?

**Comment by halvors** [comment]
The user could have remapped the SHIFT key to something else, statically setting it to SHIFT is not a solution in that matter.

**Comment by RX14** [comment]
Because sometimes you actually want to know if a player is sneaking instead of holding shift. Not ALL the time it is used for an extra modifier...

**Comment by gjgfuj** [comment]
Yeah. There is reasons why you'd want to know if the player's sneaking.

**Comment by Victorious3** [comment]
Indeed, if he maps the shift key to something else your key binding would also change. That's the thing about key bindings. @gjgfuj What reasons?

**Comment by calclavia** [comment]
MC Plugin maybe?

**Comment by gjgfuj** [comment]
As an example... OpenBlocks elevators. Sneak to go down, jump to go up.
Plus, it makes MUUCH more sense. Say sneaking becomes a toggle or anything
else. That'd break the keybinding thing. You shouldn't rely on keybinds for
anything except when you really need it. I.e. your mod's stuff.

**Comment by Victorious3** [comment]
@gjgfuj Then again, other games might not have it so that you can't rely on it anyways.

**Comment by gjgfuj** [comment]
Optional<Boolean>?

**Comment by RX14** [comment]
Put this in MC plugin.
