### ISSUE TITLE
Blocks need a Collider component to render

### ISSUE THREAD

**Issue by Dynious** [NOVA-Team/NOVA-Core#130]
Title says it all. Seems not logical. I might want to make a block render but not collide with anything.

**Comment by RX14** [comment]
And if it IS required, error nicely.

**Comment by calclavia** [comment]
@Dynious You can use a StaticRenderer, not a StaticBlockRenderer. The thing is, a collider is required if we are to specify the bounds to render. I agree with you that something has to be changed to make that more modular/clear.

**Comment by anti344** [comment]
Make collider optional and if it's not present(or specified not to be present - soul sand fe) then render standard 1x1x1

**Comment by anti344** [comment]
Hmm..
No, my PR is wrong, heck. If i wan't It to render differently from my collider(soul sand fe again).

Just add Cuboid field to StaticBlockRenderer. By default it is Cuboid.ONE, and you could change it with chainable setter. And it is used to render without bothering with colliders at all.

**Comment by anti344** [comment]
Fixed in #135, notice me =D
