### ISSUE TITLE
Using hookBasedOnEntity always returns the same orientation/direction

### ISSUE THREAD

**Issue by jimmyh77** [NOVA-Team/NOVA-Core#132]
Doesn't matter which rotation the player is at then placing the block, the problem seems to happen in calculateDirectionFromEntity.

This line always returns 0;
int l = (int) FastMath.floor((entity.rotation().getAngles(RotationUtil.DEFAULT_ORDER)[0] * 4.0F / 360.0F) + 0.5D) & 3;

Repeatable with the advanced example from http://novaapi.net/docs/Mod%20Development/Blocks/

Change the orientation hoot to hookBasedOnHitSide

**Comment by jimmyh77** [comment]
Finally got around to testing your fix, some thing isn't quite right though.

The orientation of my block seems to be flipped, so if I'm facing North then my block gets set as South.
Using the getTexture method from then advanced example http://novaapi.net/docs/Mod%20Development/Blocks/ my textures appear correctly.

If I'm facing South then my block get's set at North, textures appear correctly.

If I'm facing West, my block gets set at East, however my textures are not correct.  The front(North) texture is on the opposite side of the block.  The same happens when I'm facing East.

Should the getTexture method be looking at the Orientation of the block to set the correct texture?

Or is the switch statement enough for it to work?

**Comment by AEnterprise** [comment]
maybe to make things easy a relative direction for the texture getter? like front, back, left, right, top and bottom?

**Comment by calclavia** [comment]
@jimmyh77 Change the setting in Orientation "flip".

@AEnterprise Well, you can simply rotate your model in the render to have the correct default rotation easily.

**Comment by jimmyh77** [comment]
Changing the flip and has made the east/west work and the north/south not work

**Comment by calclavia** [comment]
Cannot replicate. Can anyone else replicate this?

**Comment by calclavia** [comment]
Reopen when the issue can be replicated again.
