### ISSUE TITLE
UV mapping seems to fail for items randomly under 1.8 minecraft

### ISSUE THREAD

**Issue by clienthax** [NOVA-Team/NOVA-Core#146]
I have 17 items registered on a creative tab, 5 on the other,
the tab with 17 items seems to have 1 of two items fail uv mapping and revert to the lava texture,

![](http://i.imgur.com/kQylgdP.png)
![](http://i.imgur.com/9hpzGSy.png)

The item affected seems to change with each client reload,
on 1.7 the items appear fine
![](http://i.imgur.com/fR683w8.png)
No error messages appear in log.

Repo: https://github.com/clienthax/PixelUtilitiesNova

**Comment by clienthax** [comment]
Just noticed that both of the texture identifiers for these items were pointed to the same png file accidentally, might be a race condition on reading the file?

**Comment by calclavia** [comment]
It might... That's weird. Is the alternation predictable or random?

**Comment by Kubuxu** [comment]
@clienthax are you using same texture but you register it multiple times?

**Comment by clienthax** [comment]
@Kubuxu yeah the two instances were pointed to the same file accidentally, still seems like a bug however

**Comment by calclavia** [comment]
@clienthax  It shouldn't register the same texture twice.. What are the names of the two texture files that fail?

**Comment by clienthax** [comment]
@calclavia bugBadge and steelBadge both point to bugBadge in the issue, https://github.com/clienthax/PixelUtilitiesNova/blob/421e2189d37ad3a0d24652d267d5c92480832999/src/main/java/com/pixelmonmod/pixelutilities/textures/TextureDatabase.java#L63

**Comment by calclavia** [comment]
@clienthax You can't register the same texture twice. Use only one instance!

**Comment by Kubuxu** [comment]
On the other hand it shouldn't fail silently.

**Comment by clienthax** [comment]
@calclavia yeah i said accidentally :P, seems odd that it wouldnt just fetch the already stored instance however no ?

**Comment by calclavia** [comment]
@clienthax Should we fetch the stored one, or crash it?

**Comment by clienthax** [comment]
@calclavia i think throw up a warning into the log and fetch the stores one, its easier to see the mistake in a itemtab atleast if two of them show up the same,

**Comment by Caellian** [comment]
@calclavia This should probably be fool-proved somehow. It might (almost definitely) happen very often when NOVA is more commonly used by mods.
When initializing new textures, NOVA should check if one has already been initialized and return if it it was, otherwise create a new one and store is in HashMap<String, Texture> (texture location -> texture) from which it did checking in a first place. Or make a system allowing multiple ids to use the same texture in OpenGL, I don't see a problem there - or is this a Minecraft-only thing?
