### ISSUE TITLE
TCN Models render in inventory differently on 1.7 and 1.8

### ISSUE THREAD

**Issue by clienthax** [NOVA-Team/NOVA-Core#147]
![](http://i.imgur.com/Op5TDSr.png)

**Comment by asiekierka** [comment]
BuildCraft-mc18 has had the same issue. It turns out that 1.8 block rendering code by default applies a different rotation to the item than 1.7.10.

**Comment by Kubuxu** [comment]
Moved to NOVA-Team/NOVA-Wrapper-MC#58.
