### ISSUE TITLE
Is NOVA development team going to release NOVA versions on GitHub too?

### ISSUE THREAD

**Issue by Caellian** [NOVA-Team/NOVA-Core#150]
By GitHub I mean [here](https://github.com/NOVA-Team/NOVA-Core/releases).

**Comment by RX14** [comment]
Yes we will, each release will be tagged. Whether we upload artifacts is kinda pointless. Devs will use maven and users... Curse?

**Comment by Kubuxu** [comment]
And our website.

**Comment by RX14** [comment]
Release notes and a link to our website to download. That's all I think.

**Comment by Caellian** [comment]
I think releases should definitely be posted on Curse so that Curse Voice and Modpack Devs can handle dependencies properly.

**Comment by RX14** [comment]
I kind of hate curse. Probably best for the project to upload it however.

**Comment by Caellian** [comment]
Why do you hate curse?

Also, providing a compiled version of NOVA with GitHub releases would allow you to use GitHub link for your website. (GitHub uses [AWS](aws.amazon.com/))

**Comment by Kubuxu** [comment]
We will have tags either way, if there will be nice and easy way to hook it up to CI we might do it.

**Comment by gjgfuj** [comment]
I vote curse as well, because then if we distribute it there we can setup
it as a dependency.

**Comment by RX14** [comment]
I hate curse as a company, and that curse is totally monopolising the mod distribution for commercial gain.

On the other hand we are open source, people can just upload it anyways so we might as well do it right.

**Comment by asiekierka** [comment]
Before you upload NOVA on Curse, please read the Terms of Service very carefully and make sure nothing bad is in it.

**Comment by Kubuxu** [comment]
I remember that we found there few shady lines.

**Comment by Caellian** [comment]
@asiekierka That is a good suggestion. You probably want to make sure they don't somehow claim your code or do something similar/evil.
I guess you are correct @RX14 , but you still have to keep in mind that people will use Curse Voice a LOT from now on considering it's extremely easy to set up modpacks using it.

**Comment by Caellian** [comment]
User submissions, 3rd point:
"By submitting, posting or displaying User Submissions on, to, or through Curse Websites (or its successors and affiliates), you grant Curse, Inc. a worldwide, non-exclusive, transferrable, royalty-free right to use, reproduce, distribute, display, perform, make derivative works of (except with regard to Submitted Projects), transmit or otherwise utilize such User Submissions on Curse Websites (or its successors and affiliates). In addition to the foregoing, you grant Curse the right to syndicate User Submissions and use User Submissions in connection with any service offered by Curse, Inc. With regard to User Submissions known as “add-ons”, "maps", "mods", or other types of Projects submitted through CurseForge.com or sites powered by CurseForge (“Submitted Projects”), the aforementioned rights granted by you terminate once you remove or delete such Submitted Projects from Curse Websites. You also acknowledge that Curse, Inc. may retain, but not display, distribute, or perform, server copies of Submitted Projects that have been removed or deleted. You acknowledge that the rights granted to Curse to User Submissions other than Submitted Projects are perpetual. In addition you acknowledge and grant users of the Curse Websites a non-exclusive license to access your User Submissions through the Curse Websites (or its successors and affiliates) and to use such User Submissions as applicable by their respective licenses."

User submissions are "including, without limitation, bulletin board postings, forum postings, artwork, photos, writings, illustrations, music, audio, sound effects, video, sketches, graphics, audio-visual works, software, code and algorithms "

This sounds really interesting....

**Comment by calclavia** [comment]
I've calculated a while ago. Technically, putting ads on our own site generates more revenue than putting it on Curse (if revenue is what we're looking for).

**Comment by RX14** [comment]
I think we need to put just the minecraft wrapper jar on curse. The wrapper jar will have the core as a fatjar I assume, or download it like the other wrappers.

**Comment by AEnterprise** [comment]
having a wrapper that can download core on curse would be a good idea, on curse if you upload a file you can mark another project as a required library, if people use curse voice to install mods then the required library will automaticly be downloaded, making it alot easier for users that never heard of nova before

**Comment by RX14** [comment]
I don't think that the terms with curse grant them much more than the LGPL already does.

**Comment by gjgfuj** [comment]
Yeah, also revenue is not what were after, moreso the publicity and ease of
use. I wanna put my mods on curse, but I can't really do that if nova
isn't. I mean I can try, but its more confusing to the user.

**Comment by calclavia** [comment]
Alright. I'll leave it to @RX14 to set that up.

**Comment by Caellian** [comment]
Wrapper shouldn't be a fatjar, it should download needed parts of NOVA dynamically before nova mods are loaded so that unnecessary parts of NOVA aren't loaded for nothing.

**Comment by Kubuxu** [comment]
@Caellian fatjar as including NOVA dependencies not plugins.

**Comment by Caellian** [comment]
Ok, that's fine I guess. As long as you're allowed to.

**Comment by RX14** [comment]
We build on open source components. We are allowed to redistribute. Also I think it's easier to distribute the core jar with the wrapper too.
