### ISSUE TITLE
Crash if there is no texture for dynamic renderer

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#165]
https://github.com/NOVA-Team/NOVA-Wrapper-MC/blob/master/1.8/src/main/java/nova/wrapper/mc18/wrapper/render/FWSmartModel.java#L47

**Comment by Caellian** [comment]
Link is broken.

**Comment by RX14** [comment]
Because that repo no longer exists, @calclavia should have screenshotted the descussion :(

**Comment by Caellian** [comment]
What is happening? I'm confoused.... Why was the wrapper repo removed?

**Comment by RX14** [comment]
We merged the core and wrapper repos, the wrappers are now in the minecraft folder in the core repo.

**Comment by ExE-Boss** [comment]
Resolved by #239 in file FWSmartModel.java at lines 80 and 81.
