### ISSUE TITLE
Don't group events in one file, one class per event

### ISSUE THREAD

**Issue by kashike** [NOVA-Team/NOVA-Core#176]
https://github.com/NOVA-Team/NOVA-Core/blob/master/src/main/java/nova/core/event/GlobalEvents.java

`GlobalEvents.WorldEvent.Load` -> `WorldLoadEvent`

**Comment by RX14** [comment]
I much prefer the first method, it fits in with the Java namespacing system and as long as we keep it consistant, it shouldn't be hard to find.

**Comment by calclavia** [comment]
@kashike I can understand it's redundant to do GlobalEvents.WorldEvent. Alternatively, we could do WorldEvent.Load. WorldLoadEvent will create too many classes.

**Comment by RX14** [comment]
Also should we put enets in one package, not have some inside Block?

**Comment by calclavia** [comment]
@RX14 That's fail. BlockEvent.Something also works...

**Comment by Caellian** [comment]
I think all events should be inside of the same package so that they are
easy to find. Event format doesn't really matter then because you can find
all of the events easily enough. Although I do think that WorldEvent.Load
is probably a way to go because it won't overcrowd the package and a slight
bit of categorization will make it easier to access events in case you
don't remember their full name or something similar.

**Comment by gjgfuj** [comment]
If they're events specifically for blocks to listen to, does it really make
sense for them to be with events for the world to listen to? Not really.
Block events in the block package, world events in a world package, etc.

**Comment by Caellian** [comment]
Yes, but you can categorize them inside of event package. Spreading them
across multiple packages makes it hard to find them if they're not in a
central place where all the others are. Nobody is preventing you from
creating blocks package inside of event package or do something similar. If
they already are categorized like this, I'm sorry.

>

**Comment by gjgfuj** [comment]
But.... You don't use them from the same place the others are. You can only
use a block event from a block, while world stuff can be in an event
package since it can be used anywhere.
