### ISSUE TITLE
Use a proper package

### ISSUE THREAD

**Issue by kashike** [NOVA-Team/NOVA-Core#177]
`net.novaapi` for example :p

**Comment by RX14** [comment]
This means we have to basically refactor everything, not really againt it: it doesn't break NovaGradle like last time.

**Comment by calclavia** [comment]
I don't like "net.novaapi". Ugly namespace "novaapi" identifier since that means Neatly Organized Voxel API API. OCD.

**Comment by kashike** [comment]
@calclavia you/someone chose the domain :woman:

**Comment by calclavia** [comment]
@kashike @stanhebben chose it...

**Comment by RX14** [comment]
Also, there are not really any available domains, so we took the best we got.

@calclavia AFAIK we made a group decision...

**Comment by Kubuxu** [comment]
Yup, it was best we could think of available domains.

**Comment by Caellian** [comment]
Don't conventions say it should be the domain of official project/group
website?
In which case it should be net.novaapi.
Or at the very least net.novapi or something like that.

**Comment by stanhebben** [comment]
It's certainly a convention, and I believe it is also a requirement for any project on maven.

The domain name was chosen together. After it was chosen, I reserved it (and paid for it, and will keep it funded).

**Comment by SoniEx2** [comment]
You should've chosen novapi.net (Neatly Organized Voxel Application Programming Interface). It doesn't sound as good but at least it doesn't have API twice.

**Comment by Caellian** [comment]
Well, nova.net is taken, but novapi.net seems fine.

**Comment by SoniEx2** [comment]
RAS syndrome.
