### ISSUE TITLE
Data storage is not working correctly

### ISSUE THREAD

**Issue by Kubuxu** [NOVA-Team/NOVA-Core#179]
I have code:

``` scala
@Sync(ids = Array(0))
@Store(key = "side")
var _side: Byte = 0

@Sync(ids = Array(0,1))
@Store(key = "size")
var size = 1

@Sync(ids = Array(0,1))
@Store(key = "isMaster")
var isMaster = true

@Sync(ids = Array(0,1))
@Store(key = "masterOffset")
var masterOffset = Vector3D.ZERO
```

I get following stacktrace:
http://hastebin.com/xisolepiku.avrasm

**Comment by Caellian** [comment]
To clarify it seems as if code is trying to set boolean value to a byte.
Considering syntax seems to be correct, it is almost certainly annotations
fault. Error is in the first variable so others might not be important.

**Comment by Kubuxu** [comment]
It is possible that naming is broken and `_side` is assigned first possible value or something like that.

Also _side seems to get saved so it is probably previously assigned correct value.

**Comment by ExE-Boss** [comment]
It is actually caused by `DataWrapper`/`DataConverter` creating only one `isBoolean` entry in the NBTTagCompound, which causes all the other `byte`s/`boolean`s be treated as what is in the `isBoolean` entry, thus causing a `ClassCastException` on load.
