### ISSUE TITLE
More dependency filtering options

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#186]
There should be a way to make a mod load both AFTER and BEFORE other mods, e.g. load a mod after Thaumcraft but before BuildCraft.

**Comment by RX14** [comment]
See #141

**Comment by SoniEx2** [comment]
Still only lets you specify after...

Is it too hard to do a before?

**Comment by RX14** [comment]
No, but I was bringing those proposals to your attention so you could comment on them. Allowing you to hook before should be good.

**Comment by calclavia** [comment]
Yeah, see #141

**Comment by SoniEx2** [comment]
Doesn't provide what I need.

**Comment by calclavia** [comment]
@SoniEx2 The problem with having BEFORE is cycle dependency. I think @asiekierka originally said that we should only do load after... I might be wrong.

**Comment by SoniEx2** [comment]
Fully doable with AFTER as well.

Mod A depends on Mod B. Mod B depends on Mod A.

**Comment by anti344** [comment]
Well, i hope no mods are so stupid, soo..

mod A depends on mod B, mod B depends on mod C, mod C depends on mod A
