### ISSUE TITLE
Make .gitignore modular

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#200]
Instead of having a single gitignore for everything, the gitignore should work as follows:

First, everything should be ignored, like this:

```.gitignore
*
```

All subfolders should be unignored like this:

```.gitignore
!/folder/.gitignore
```

Inside each subfolder's .gitignore you'd unignore wanted files. E.g. src folder:

```.gitignore
!*
```

This gives you better control over the ignored files.

(Or something like this... Not sure if you need to unignore each subfolder and put * in each .gitignore)

**Comment by liach** [comment]
Why not to open a PR?

**Comment by RX14** [comment]
Haaave you looked at this repo AT ALL?

https://github.com/NOVA-Team/NOVA-Core/blob/master/minecraft/.gitignore 
https://github.com/NOVA-Team/NOVA-Core/blob/master/minecraft/1.7/.gitignore 
https://github.com/NOVA-Team/NOVA-Core/blob/master/minecraft/1.8/.gitignore

**Comment by SoniEx2** [comment]
What about all the other subfolders?

**Comment by RX14** [comment]
None of them have enough subdirectories to really need something such as this.

**Comment by liach** [comment]
Oh yes it was done in #1 already...
