### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by liach** [NOVA-Team/NOVA-Core#205]
Is Nova still active? It did not update in last 3 months.

**Comment by RX14** [comment]
We are in the unfortunate position that our main developer, @calclavia is very busy with college.

**Comment by liach** [comment]
Okay thanks. Btw how much of the api has finished?

**Comment by RX14** [comment]
The API is complete enough to recreate calclavia's mod [Electrodynamics](https://github.com/calclavia/Electrodynamics) in. Unfortunately the Electrodynamics mod isn't quite up to date with the latest version of NOVA so you can't use it as a reference to learn the API from really.

**Comment by RX14** [comment]
Actually, I take that back, Electrodynamics is up to date with the latest NOVA snapshot.

Still in scala though.

**Comment by calclavia** [comment]
@RX14 I can confirm :)

**Comment by Caellian** [comment]
If I didn't start writing a direct Minecraft framework for NOVA, I would
consider getting more familiar with the project and code and contributing
to it. As it is now, NOVAL is extremely big (for one person) - I admire you
Calclavia for doing so much on your own.

**Comment by calclavia** [comment]
Yeah, it's too big of a project for me to take on myself.

**Comment by Xen1290** [comment]
@RX14 Electrodynamics doesn't work with NOVA, see
https://github.com/calclavia/Electrodynamics/issues/16

**Comment by RX14** [comment]
Well it compiles.

**Comment by Xen1290** [comment]
@RX14 Yes, but NOVA gives an error in console, in that issue there is only the crash report generated from that error.
EDX is no longer developed, so it's dead unfortunately, i really liked EDX/Resonant Induction/Atomic Science...
So i don't know if it's NOVA or EDX

**Comment by RX14** [comment]
Yeah I think it's an error with NOVA's scala detection.

**Comment by Xen1290** [comment]
Will be fixed? I tried everything to get working that mod, but no results. it's the best mod I ever played(especially atomic/quantum part)

**Comment by aolko** [comment]
so, uh, still dead?

**Comment by calclavia** [comment]
Yep. Still dead.

**Comment by aolko** [comment]
care to revive? Or you are going to leave it to minecraft modder archeologist group of the future?

**Comment by skyem123** [comment]
@aolko, sadly @calclavia said that
> Yeah, it's too big of a project for me to take on myself.

This means that because the developer who has the most understanding of the code cannot do it themself, and due to the fact that people who are interested don't understand the code, NOVA is kinda trapped in a situation which is impossible to get out of.

**Comment by RX14** [comment]
University basically destroyed the development team.

**Comment by aolko** [comment]
so, no option for "rewiring" things back in place (to a working state) (maybe even reverse-engineering the whole thing?)

**Comment by calclavia** [comment]
@aolko The code is there. It worked with MC 1.8. Feel free to dig through it. Javadocs are there for many parts of the code and it's written in a fairly self-explanatory way.

**Comment by Falconerd** [comment]
@calclavia Probably can't for a while as I'm super busy atm, but would you be open to merging pull requests assuming we keep to the design philosophy of NOVA?

**Comment by RX14** [comment]
@Falconerd of course!

**Comment by RX14** [comment]
If you need any help ask on #NovaAPI on espernet irc.

**Comment by Falconerd** [comment]
@RX14 Cheers, I had a quick look and it seems that most of the code is well documented. I'm looking forward to digging into it.

**Comment by calclavia** [comment]
@Falconerd As one of the main devs, I'm happy to give advice as well.

**Comment by TekkitCommando** [comment]
@RX14 @calclavia So if this is still at a stalemate I know Java, I could possibly make a few mods with Nova and try to get familiar with it and then try to continue it. I was planning on making my own API for Minecraft modding but it's better to work on one already made. :) If I figure out like I hope to you should see PR's in the future, maybe enough to get me added to the Nova team.

**Comment by liach** [comment]
@TekkitCommando I hope you can integrate nova api into Glowstone.

**Comment by Xen1290** [comment]
And maybe if you can port electrodynamics and other calclavia's mods to 1.9 would be good!

**Comment by TekkitCommando** [comment]
@liach I am no longer part of the Glowstone++ team but I may send a PR or talk to mastercoms about that at some point when I get my head around Nova. @Xen1290 Yeah maybe, but it would be a quite heavy recode since I am not really familiar with Scala so it will probably be in the future but I do plan to try to recreate Electrodynamics and the others at some point.

**Comment by skyem123** [comment]
@TekkitCommando, well... if you can get Electrodynamics running on NOVA, and NOVA running on 1.9... :tada: :P

**Comment by TekkitCommando** [comment]
@skyem123 Yeah, I have a few friends that may be able to help with the Nova updates and what not but i'm not sure. I do know I am gonna need a considerable amount of time and some heavy practice with this API so don't expect a 1.9 update in a couple weeks or something like that xD

**Comment by RX14** [comment]
@TekkitCommando can you make it to `#NovaAPI' on `irc.esper.net`?

**Comment by TekkitCommando** [comment]
@RX14 Um yeah sure :D

**Comment by liach** [comment]
Can be closed 😄
