### ISSUE TITLE
Wrappers shouldn't be in Core

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#209]
Wrappers should be in their own repos, separate from Core.

The Minecraft wrapper should be in NOVA-Wrapper-Minecraft with different branches for different MC versions.

**Comment by RX14** [comment]
We discussed this at length in IRC and we decided that it's much much much easier this way. Wrappers do not *have* to be in the repo but the official ones are so that wrappers are always in sync with the API.

**Comment by SoniEx2** [comment]
It does however make it a pain to figure out how to make a custom wrapper going by the official wrappers.
