### ISSUE TITLE
NOVA is too tied to Minecraft

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#211]
Currently, NOVA is too tied to Minecraft, so it's hard to use it for other things. I'd like for that to be changed.

**Comment by asiekierka** [comment]
It's tied to voxel game design in general, and at least the Terasology devs *were* watching.

**Comment by SoniEx2** [comment]
Really? Because the docs told me to use MC or gtfo...

**Comment by calclavia** [comment]
We don't have wrappers for other voxel games. You could write a wrapper for another game.

**Comment by asiekierka** [comment]
Yes. The Wrapper only exists for Minecraft. The Core is game-agnostic. Please do proper research or ask around before you open an issue.

**Comment by RX14** [comment]
If anything the level of abstraction was NOVA's downfall...

**Comment by calclavia** [comment]
@RX14 Actually I think the lack of developers was its downfall.

**Comment by RX14** [comment]
Well it's a combination of both. Too much work for too little developers. Maybe if we had released a working prototype before you ran out of time, we could have attracted some developers to work on the core. It hardly matters now, I can only hope to fix the build and get maven working in the hope that someone else is able to work on it.
