### ISSUE TITLE
Get rid of reflection

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#217]
Reflection in core means core cannot be used with things that disallow reflection. Reflection-based convenience bullshit should be a separate module/plugin (`NOVA-HL` or `NOVA-HiddenCost` maybe?).

**Comment by RX14** [comment]
no

**Comment by SoniEx2** [comment]
Please reopen. My game has a SecurityManager which disallows reflection.

**Comment by calclavia** [comment]
@SoniEx2 Why do you disallow reflection?

**Comment by SoniEx2** [comment]
Because it's slow. Remember my game uses SQLite for performance and stuff.

**Comment by RX14** [comment]
As I stated in IRC, come back to me with a profiler trace showing how much of a performance impact reflection has on your game, then we can talk with numbers instead of hypothericals. I think removing reflection and replacing it with an annotation processor may be a premature optimisation, so I would like to get some numbers on the issue before pursuing it further.

**Comment by asiekierka** [comment]
Premature optimization is the root of all evil, as they say. A neglible
performance increase is not worth a single additional hack.

2016-08-25 12:18 GMT+02:00 Chris Hobbs <notifications@github.com>:

**Comment by SoniEx2** [comment]
Having a hack that is not needed isn't worth it either. KISS, remember?

Why not KISS and let the mod author implement saving/loading of storables? The automatic saving/loading mechanism is kinda wonky anyway.

Actually, why even apply those reflection hacks at all? Why not add `DuplicableComponent`s and `ComponentInt(name, defaultValue)`, `ComponentLong`, etc, which all implement Storable, then iterate components with instanceof Storable and stuff?

KISS, no hacks, works anywhere.

**Comment by calclavia** [comment]
I personally think it's a decent idea to separate things out into more modules. If you think the NOVA Storage API doesn't belong in core, it could be made into a separate module.

**Comment by SoniEx2** [comment]
I can't tell whether it should be in core.

I can only say the current API isn't the best, and should be more dynamic.

**Comment by SoniEx2** [comment]
@calclavia It would perhaps be best to have states (i.e. a fixed set of metadata) as part of core, but storage (dynamic metadata) as part of a separate plugin.
