### ISSUE TITLE
[RFC] "SuperNOVA"

### ISSUE THREAD

**Issue by SoniEx2** [NOVA-Team/NOVA-Core#225]
I believe NOVA-Core should be split into a library called "SuperNOVA". This library should be a *library* rather than a framework and it should provide things such as:

- BlockPos class/interface
- Block class/interface
- World class/interface

But NOT:

- Mod interaction interfaces
- Mod loading
- Adapters/converters
- Etc

This library should have no external dependencies. This library would be designed for use by split mods.

Split mods are mods which are split into "library" and "implementation". SuperNOVA would be geared at the "library" part.

Unlike NOVA, SuperNOVA would be lightweight, self-contained (i.e. can run in a sandbox, doesn't load mods, etc) and it'd leave implementation details up to the user (for shadowed jars) and/or engine. SuperNOVA would not have "wrappers".

**Comment by SoniEx2** [comment]
Unresolved questions:

- What's the license?! D:<
- Should we move stuff from NOVA-Core to it? (**requires** LGPLv3 as the license) Or should we redesign from scratch? (would probably be better, as this is a huge change)

**Comment by asiekierka** [comment]
I'm afraid the answer to "a project died because it was too overcomplicated" is not "let's make it *more* complicated". Sorry.

**Comment by SoniEx2** [comment]
I don't wanna make it *more* complicated. I wanna simplify it.

I need that "small set of abstractions" library, but I don't want a "fully-featured modding API". With the former, you use the game's normal modding API, but your code can be *easily ported* between games, which is the feature I want. With the latter, you're doing Java all over again ("write once, run anywhere").

**Comment by RX14** [comment]
@SoniEx2 If you don't want to use NOVA, don't use NOVA.

**Comment by SoniEx2** [comment]
@RX14 I do want to use NOVA, just... in a sandbox...

**Comment by RX14** [comment]
You can use NOVA in a sandbox, and your wrapper can choose not to use most of the features in core. NOVA core doesn't do classpath introspection or mod loading.

**Comment by SoniEx2** [comment]
I can have NOVA-Core without NOVA-Core?
