### ISSUE TITLE
Allow (de)serialization of Data using JSON

### ISSUE THREAD

**Issue by ExE-Boss** [NOVA-Team/NOVA-Core#244]
This would allow for the ability to pass Data arguments to commands.

For this we could use the [JSON Processing](https://jsonp.java.net/) API.
To use it, we simply need to add the following to our build script:

```groovy
dependencies {
	compile group: "javax.json", artifact: "javax.json-api", version: "1.0"
	runtime group: "org.glassfish", artifact: "javax.json", version: "1.0.4"
}
```

**Comment by SoniEx2** [comment]
Why not GSON?

**Comment by ExE-Boss** [comment]
Because the JSON Processing reference implementation is made by [Glassfish](https://glassfish.java.net/).

**Comment by SoniEx2** [comment]
Both Minecraft and Terasology use GSON.

I'd say use GSON since those are our main targets currently.
