### ISSUE TITLE
EventBus System

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#65]
The event bus system is getting more cluttered as there are more events. Are there any ideas how to improve it?

Look at Block class.

**Comment by anti344** [comment]
There is an event bus per event, but why don't do it like Forge? One event bus handles if not all the events, but specific category(block events fe) of them/

**Comment by Kubuxu** [comment]
@anti344 now we are using lambdas to register event handlers. While designing it we didn't want to use annotation for events as they are really inflexible.

**Comment by anti344** [comment]
Register the handlers however you want to, i'm talking about lodes of EventBus'es, while Forge has just a couple of them.

**Comment by anti344** [comment]
Oh, i get it, but instead of choosing the EventBus you could just specify the parameter type in lambda to choose to which event you want to listen.

**Comment by anti344** [comment]
Hrm, maybe i played too mush with Scala, could you gather the generic type with reflection?
Or stop, you could get the parameter of method act in anonymous class(implementing EventListener) created.

**Comment by Victorious3** [comment]
@anti344 Look at the gui classes, they share one event bus for different events.

**Comment by calclavia** [comment]
Added better binding syntax: eventBus.on(ExplodeEvent.class).bind(evt -> doSomething);
