### ISSUE TITLE
Arguments for Factory

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#66]
I suggest that we don't have arguments for block factory.

However, ComponentManager may need arguments, as components need to have arguments passed in order to be constructed. Should we make Components use DI? If so, how should DI be exposed to mods?

One proposal:
Consider a new way to do factories, without dummy objects. Instead, IDs have to be registered. While this is rather clumsy, it prevents problems with constructors. The obj arguments cause issues for some blocks, and becomes clumsy.

It is nicest (most style points) if modders can instantiate blocks by doign the following:

BlockStone stone = world.set(pos, new BlockStone());

**Comment by Victorious3** [comment]
You could have a look at the methods I added to ReflectionUtils a while ago, they are capable of instancing a class type like the JVM would, by searching for a matching constructor for a given array of arguments without the need to specify the type classes specifically. Might be of use here to do some magic in the background.

**Comment by calclavia** [comment]
This is becoming a problem when I register with dummies and stuff, as it gets really ugly.
```java
//Registers Redstone Node
//-100000000000000000000 stylepoints
		componentManager.register(args -> args.length > 0 ? new NodeRedstone((Block)args[0]) else new NodeRedstone(new Block() {
			@Override
			public String getID() {
				return "dummy";
			}
		});
```

**Comment by Victorious3** [comment]
I don't like dummy objects at all... I'd rather use IDs... I'll have a look at this later, maybe we can do something involving reflection here.

**Comment by calclavia** [comment]
@Victorious3 Reflection is slow, according to @Kubuxu, it may be a problem as well. I agree with you and I do not like dummy objects. Class registrations are cleaner.

**Comment by Kubuxu** [comment]
Reflection is not as fast as normal code because it can't be JITed as well. Also you should never perform reflection lookup in loops as it is the slowest part.

**Comment by calclavia** [comment]
Yes, thought the dummy system we have with all the factories seems to be a bit annoying. We need arguments for some factories, that's an issue...

**Comment by calclavia** [comment]
I was reading some silk DI docs, and I'm wondering if we can use DI with factories.

Something like:

World.setBlock(pos, BlockStone.class) seems the most appealing.

Or...

World.setBlock(pos, Factory.of(BlockStone.class).with(Argument))

Also, saving instance of block factory gets quite annoying. I'm trying to think of the most idiomatic way to set blocks.

I also made a related issue for components and all other registries.

**Comment by calclavia** [comment]
https://github.com/NOVA-Team/NOVA-Core/issues/102
