### ISSUE TITLE
Fix exceptions in Nova initialization not printing

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#67]

**Comment by RX14** [comment]
I'm sure this is a fml/Forge bug.

**Comment by Victorious3** [comment]
@RX14 Its actually google's event bus, but doesn't really matter as we can try catch it either ways.

**Comment by RX14** [comment]
AFAIL this was fixed in 5514c090

**Comment by RX14** [comment]
AFAIK this was fixed
