### ISSUE TITLE
Custom JavaDoc for Implementation Details (Vic)

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#68]
Many wrapper specific tasks have to be implemented in a way that exceeds the simple overriding of interface methods. Its necessary to provide additional information to make sure that every wrapper agrees to a set of conventions, and instead of putting it at the end of the usual javadoc comment, a custom tag makes it clear.
I would vote for @implNotice.

**Comment by anti344** [comment]
Comment on every issue! lol =P

**Comment by RX14** [comment]
I say that this should be in the docs repo as a "notes to wrapper devs" section,  not in the javadocs.

**Comment by Victorious3** [comment]
@RX14 Yeah, and you are going to be the one looking it up for every method you implement. Let it stay where its needed. The wiki is for actual explaination and not two lines of notes for every method.

**Comment by RX14** [comment]
Well it depends how long the notes are. I see your point though. Go add this into the java doc task.
