### ISSUE TITLE
World Generation

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#71]
Consider making it a plugin.

**Comment by halvors** [comment]
@calclavia Yeah, all voxel games doesn't necessarily have world generation. So a plugin is :+1:

**Comment by gamemanj** [comment]
But are you sure they don't? The world in which a voxel game is played must be created somehow.

**Comment by gamemanj** [comment]
It would bloat the core too much to put this there, though.
I'm just noting that world generation exists in all voxel games in one form or another.

**Comment by halvors** [comment]
Well, the world could be predefined even if it's a voxel game. But i'm not saying i know of any.

**Comment by magik6k** [comment]
Some games may only allow to register certain things like ores instead o full generation, other can have fully closed worldgen

**Comment by calclavia** [comment]
https://github.com/NOVA-Team/NOVA-Worldgen
