### ISSUE TITLE
Sound System

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#72]
We need a better way to manage assets (textures, sound, language).

We also need a functioning sound system. The current one by @skyem123 doesn't function yet (it's only an API).

**Comment by anti344** [comment]
If strictly place them at right folders(textures, sounds, models), then we could have ResourceLocation-like class, with EnumResourceType(fe), name and modid(or mod object).
Or abstract ResourceLocation-like class with descendants like TextureResource, SoundResource, ModelResource etc, so you can specify, what you want in args.
And to create them not by constructors, but by static factory methods, like ResourceSystem.sound("my_cool_mob/moo") or ResourceSystem.model("destroyer")

**Comment by RX14** [comment]
Well, why not use URIs? they can be used with http, file and jar protocols... Then you just get the stream. Also extensible.

**Comment by calclavia** [comment]
@RX14 URIs sound good. Make it flexible so modders can define their own asset structure.

**Comment by RX14** [comment]
Well it's just a URI... We don't specify the structure

**Comment by anti344** [comment]
Ok, ok, flexibility, i remember

**Comment by calclavia** [comment]
Please assign yourself if you want to work on this.

**Comment by RX14** [comment]
The jar URL syntax is quite hefty, so some utilities for getting a URL of a file in the current jar will be needed.
