### ISSUE TITLE
Config System

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#73]
Kubuxu Suggested API: https://github.com/typesafehub/config I also suggest an annotation system: @Config annotation on fields that need to be configured via text file. I already wrote this system in

**Comment by anti344** [comment]
Like this, right? HOCON is da best.
```java
@Config("object.inner_one.new.foo.baz")
public boolean isBarActive = false; //false is default
```
```hocon
object{
  inner_one{
    new.foo.baz = true
    foo.bar : 14
  }
  yo = test string
}
```

**Comment by calclavia** [comment]
Yes... that looks nice. Now we just need a PR

**Comment by anti344** [comment]
This is actualy the one i could manage to do myself.
Let me set up NOVA workspace now =P

**Comment by Kubuxu** [comment]
It also would be useful if you could specify config prefix for whole class. Like:
```
@Config("object.inner_one")
class something {
    @Config("new.foo.baz")
    public boolean isBarActive = false; //false is default
}

**Comment by anti344** [comment]
Maybe
@Config("object.inner_one.new.foo")
public boolean baz = false;
?

In annotation you'd specify parent object(or empty string if that's the top field) and optional comment, and the name would be the name of the variable.

**Comment by anti344** [comment]
Oh and question - where is the code to process all the annotations? Or where to put it if not exist?

**Comment by calclavia** [comment]
There's no code needed. It processes automatically by looking up annotations.

**Comment by anti344** [comment]
Basic thing without classes is there, writing tests for it

**Comment by anti344** [comment]
Everything works, but for adding comments to HOCON renderer i must use hard reflection.
Looks like this for now:
```java
//for file writes defaults to file automatically,
//for string returns new string, for everything else does not generate
configs = new ConfigHolder(); //class with annotations in it
Configuration.load(file/string/uri/url, configs);
```
Autogenerated config for below class..
```java
public class ConfigHolder{

  private static class RocketHolder{

    @Config(comment = "Rocket max count")
    public int count = 5;
    
    @Config(comment = "Rocket max damage")
    public int damage = 114;
  }

  @Config("items")
  public RocketHolder rocket = new RocketHolder(); //You always should instantiate classes

  @Config("items")
  public String test = "Hello Config";
}
```
.. would look like this
```hocon
items {
  rocket {
    # Rocket max count
    count=5
    # Rocket max damage
    damage=114
  }
  test=Hello Config
}
```

**Comment by RX14** [comment]
@anti344 can you pull request it so we can see the progress, just state in the title that you don't want it merged.

**Comment by anti344** [comment]
Oh, ok
