### ISSUE TITLE
Nova Scala

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#74]
I'm going to be making a NOVA plugin called Nova Scala, with a set up Scala tools that makes it nicer to write NOVA mods (mainly moving stuff from my own library here).

Main features:
* Scala matrices (with unknown types)
* Scala main class loading (maybe extends app)

Any other feature requests?

@anti344

**Comment by Kubuxu** [comment]
Implicits?

**Comment by anti344** [comment]
InventorySeq?
I have one.
And Scala 2.12 allows to use Scala lambdas.

**Comment by anti344** [comment]
Something to do with traits i wanted, but can't remember what, ugh

**Comment by anti344** [comment]
For fun you could ASM everything to add for all getters/setters a field() and field_$eq method to make it feel like Groovy.

**Comment by calclavia** [comment]
I don't think the field_$eq works. I tried it...

**Comment by anti344** [comment]
Just field_$eq? Without field()? Or with it? In Scala code it works only if you have both of them, `field` and `field_=`

**Comment by calclavia** [comment]
Oh... I didn't put both, so maybe that's why.

**Comment by calclavia** [comment]
I've made a new repo for this. :)
