### ISSUE TITLE
Particles and Lines

### ISSUE THREAD

**Issue by Ecu** [NOVA-Team/NOVA-Core#78]
I'm sure this is something that will probably eventually be done, but I did not see a abstraction of particle rendering or line rendering in NOVA.  Figured I'd make a note of it here so that it gets looked into.

I mentioned line rendering as being able to do things like fishing poles or Immersive Engineering's power lines by giving two points and a curve would be epic.

**Comment by calclavia** [comment]
@Ecu Already there. World.addClientEntity instead of addEntity, and your entity will only be there client side.

However it's not a comprehensive particle system. That will require a plugin.

**Comment by anti344** [comment]
Yup, thats client entity, but for particles in MC there is limitations(like no more than 4000 particles, or particle setting) and special already coded-in render(so particle quad always rotated to you) and some other little cases.
