### ISSUE TITLE
Command System

### ISSUE THREAD

**Issue by halvors** [NOVA-Team/NOVA-Core#85]
Almost every voxel games does at some level have commands. This is often implemented for the player as well as the console.

I know that a lot of Minecraft Forge mods do add commands. So this should be in place in order for Minecraft Forge modders to adapt to NOVA.

**Comment by calclavia** [comment]
Plugin?

**Comment by halvors** [comment]
Well, in my opinion this is more like a core feature, and should be implemented in NovaCore. Don't you agree with that?

**Comment by calclavia** [comment]
I think this would work better if it was a plugin.

**Comment by gjgfuj** [comment]
Make everything a plugin. Everything. Except the very core features.

**Comment by calclavia** [comment]
https://github.com/NOVA-Team/NOVA-Core/issues/155
