### ISSUE TITLE
ConnectedTextureRenderer is broken

### ISSUE THREAD

**Issue by halvors** [NOVA-Team/NOVA-Core#86]
The ConnectedTextureRenderer is broken, doesn't seem to render correctly at all.

When applying this to the block like this...
`
add(new ConnectedTextureRenderer(this, myedgetexturehere));
`
Something seems wrong...

![Image](http://i.imgur.com/g5fCyzr.png)
![Image](http://i.imgur.com/nHa3Rfx.png)
![Image](http://i.imgur.com/sRe9L4a.png)

**Comment by calclavia** [comment]
Oh, it looks like it needs a translation... I haven't been able to test it properly yet.
