### ISSUE TITLE
ItemDictionary#register() not working properly

### ISSUE THREAD

**Issue by halvors** [NOVA-Team/NOVA-Core#87]
ItemDictionary.register() is not working propatly. I guess this is becuase the ItemDictionary is defined as follows:
```
public class ItemDictionary extends Dictionary<String> {

}
```
And it instead should be:
```
public class ItemDictionary extends Dictionary<Item> {

}
```
Since we are mapping String to Object, and if we specifiy String as the object it will both be String.

I've tried registering items as this:
```
Game.itemDictionary().add("itemMirror", itemMirror);
```

Where itemMiror is the Item.

**Comment by halvors** [comment]
@stanhebben This is your code, do you have any suggestions?

**Comment by RX14** [comment]
What should the behaviour of the `ItemDictionary` be?

**Comment by halvors** [comment]
Map a string to a Nova item?
