### ISSUE TITLE
Remove Native Loader

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#89]
It's redudant. Instead, add GameInfo so mods can check if certain games are loaded for specific features.

**Comment by RX14** [comment]
How would that work with dependency injection? In other languages people set defaults of null to the constructor args for optional modules. This allows them to enforce not null on requirements yet easily detect not available modules while retaining the constructor injection.

**Comment by Kubuxu** [comment]
You can request injection of Optional[UnavailableClass]

**Comment by RX14** [comment]
Uhh, can you give an example?

**Comment by RX14** [comment]
Oh, derp I get it.

**Comment by calclavia** [comment]
Finished https://github.com/NOVA-Team/NOVA-Core/commit/d8091dc965798d859696a0f9a64aa753ad5a8cd3
