### ISSUE TITLE
Plugin Project Structure

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#90]
I propose that we keep the same structure for all NOVA plugins.

For plugins that do not need native access, use standard Gradle format:

src/manjava or src/main/scala

### For plugins that DO need native access, use:

src/main/java
mc1710/src/main/java
mc1804/src/main/java
terasology130/src/main/java

Creates subprojects where each subproject is a game with a specific version. Each subproject can have its own build configuration.

Thus, I also propose that NOVA-Core act like a plugin itself. The NOVA-Wrapper-MC should be one subproject in the NOVA-Core repository, providing the wrapping for Minecraft 1.7.10. All other wrappings to other games will be subprojects in the same repository. We will have consistency this way.

### Plugins repositories should be named as such:

NOVA-Microblock
NOVA-GUI
NOVA-Fluid

Plugins should use package names: "nova.core", "nova.microblock", "nova.gui".

As well, this will make it nice when we split GUI, Fluids etc. into its own plugins, each with its own mini-wrapper in its project repository. I think the more plugins and less in the core, the better. If we're going to split, we should do it early. Plugins can depend on each other, and all plugins will depend on the Core plugin essentially.

**Comment by calclavia** [comment]
IF @RX14, @Kubuxu, @Victorious3 agrees, I will reorganize the repositories and sort things into plugins (as possible). The Gradle will probably be messed up after this (the core wrapper's gradle becomes a subproject build file), so I'll need @RX14's help.

**Comment by gjgfuj** [comment]
This sounds good to me, so I'd +1 this idea.

**Comment by Kubuxu** [comment]
Remember that too many repositories is not good too. It creates problems when synchronous PRs are needed. 

I don't like the idea of having tenths of repositories. It extends time needed to set-up, time needed to push and time required just to skim through code. How about gradle sub-projects?

**Comment by RX14** [comment]
Well, I would leave this for now. I will most likely have time to not fuck this up on the weekend. Please wait till then so I can do this properly!

I also suggest keeping the wrappers under the wrappers/ directory because it stops root folder clutter and most people don't look at the wrapper, only the core. 

Otherwise, GREAT suggestion!

**Comment by calclavia** [comment]
Yes. However, the plugins I'm talking about are rather independent. I think most likely only GUI and fluids can be cleanly split at the moment.

Subprojects may also work. But the purpose of separate repositories is that mods don't need to depend on things they don't need. That way, updates are done faster and easier.

For example, the core wrapper can be updated to 1.8 MC first, while other developers are updating other plugins. Less merge conflicts, and mods that don't depend on UI, for example, won't need to wait until Vic updates to 1.8 wrapper. It's often better to have a few who are experts at their own plugin to update their respective wrapper, than to have everyone touching code they're not familiar with.

We can discuss what features in NOVA are independent enough to be plugins, and what stays in the core. I agree that too many repositories isn't good, we need to find an appropriate amount.

**Comment by RX14** [comment]
We are **NOT** sticking every plugin in one repo.

**Comment by Kubuxu** [comment]
Sub-projects can be released is separate jars. Same as sub-sub-projects. So you could have sub-project GUI with sub-sub-projects mc1.7 MC1.8 and so on.

**Comment by RX14** [comment]
That's not the point, it's messy and basically what calclavia said...

**Comment by Kubuxu** [comment]
@RX-14 but don't you think that fluids themselves are to small for.separate repo?

**Comment by calclavia** [comment]
I agree with wrappers being in "wrapper/game_version".

If we decide to put the so called "core-plugins" as subproject, what constitutes a core plugin? Things like AI and Microblocks are not part of core. But should world gen be a core plugin (in the core repo)?

If we have subproject plugins, NOVA-Core would look like this:

core/src/main/java
core/fluid/src/main/java
wrapper/mc1710/core/src/main/java
wrapper/mc1710/fluid/src/main/java
wrapper/mc1804/core/src/main/java
wrapper/mc1804/fluid/src/main/java

And yes, we'll leave this to the weekend since I'll need @RX14 to be active.

**Comment by gjgfuj** [comment]
BTW, probably the most common synchronous PR that exists now is wrapper +
core. And those exist anyway. So merging those together would help a lot.
This would make it a lot cleaner.

**Comment by gjgfuj** [comment]
Also, I'd probably say worldgen should be a plugin, as should everything
but essentials. Separate repos should be made for each plugin IMO, as if
they're not an important part of the project, they shouldn't be included in
the same repo.

**Comment by calclavia** [comment]
I agree with separate repos, given that we don't need ton of them. It's most organized that way and if one modules fails, not everything fails. I suggest we measure how many repositories we have and make decent sized repos. But if the plugin is one class, it isn't worth making a repo as @kubuxu mentioned.

**Comment by gjgfuj** [comment]
Yeah, true. If its just one class i'd probably just package it with the
core.

**Comment by RX14** [comment]
I believe that every plugin would have its own repository. If you believe that you are making too many repos then you are moving too many things out of core.

You should be able to make about half of current mods using just the core, as a rule of thumb I think.

**Comment by Victorious3** [comment]
I wouldn't bundle the wrappers with core as they are two completely separate entities. It may work as long as there is only a Minecraft wrapper, but imagine 10 different ones in possibly different languages even. I imagine that most of them would be independent anyways, so they wouldn't be included. Also, core and implementation are two completely different things, while a PR for core might be completely valid, the implementation might lack. They should indeed be two separate PRs.

**Comment by calclavia** [comment]
You'll simply get wrapper/GAMe_NAME/src/main/java though. It's not really a mess compared to 10 wrapper repos. It makes more logical sense to bundle by feature/plugin than by "NOVA and its wrapper"

**Comment by Victorious3** [comment]
@calclavia Say, what do wrapper and core have in common? Other than that the wrapper depends on core, I mean.

I just imagine X run configurations with X different games in my tiny workspace and think that it would become overbloated. I also don't think its possible to implement a feature for all of those wrappers, as many of those games will work completely different. This is going to work as long as there's only Minecraft, but at some point we have to get used to a feature in core that's implemented on some of the wrappers, and then wait for all of them to adapt. Having them all in the same repo doesn't make it magically faster, on the contrary, if somebody only works on one of them there is no point in shipping the configuration for X different games including setup time and everything.

Another thing is the issue tracker, and everything that comes with a repo. Pull requests are going to be a horror, and the issues? Don't want to think about it. Honestly, I don't see any benefit of them being in the same repo other than not having to commit to multiple ones of them. In which case, as mentioned before, it makes sense to review the implementation separately for every one of the wrappers and core. 

Besides, I think that working on multiple ones at the same time won't happen much in the long run, which makes the entire speed advantage obsolete.

**Comment by RX14** [comment]
I have changed my mind and totally agree with @Victorious3. Combining the wrappers means combining the issues which is just wrong.

**Comment by gjgfuj** [comment]
And this is why, (as I've been saying), the core should only contain common stuff that is NOT OPTIONAL. i.e. blocks/items/important stuff. So anything that's part of core, should be something that is /required/ to exist on the wrappers' side. Not something that /may/ exist on the wrappers side, that should be a plugin. Only the simplest mods should be doable without plugins.

**Comment by RX14** [comment]
@gjgfuj :+1:

**Comment by Victorious3** [comment]
@gjgfuj Which is a huge thing by itself. Rending works completely different on each of those wrappers, so does everything else. I mean, just look at the size of the wrapper.

**Comment by Victorious3** [comment]
Honestly, having a giant repo like this sounds like an unmanageable task. It doesn't make sense to separate plugins and then throw this together.

**Comment by RX14** [comment]
Thinking again repo spam isn't hard to deal with. Many organisations have hundreds of repos and with a good manager like `gr`, managing this many repos isn't hard.

**Comment by gjgfuj** [comment]
I'd still want to stick to having the core+wrappers(for core) in one repo. But splitting AS MUCH AS POSSIBLE out of core. We want each plugin to be as /lightweight/ as possible, so as to allow games to only implement features they need.

**Comment by RX14** [comment]
I truly believe that with proper tooling and gradle magic splitting this into a thousand repos wouldn't be too difficult.

As @Victorious3 said, after we get a wrapper that isn't minecraft this repo scheme will fail.

**Comment by gjgfuj** [comment]
That is true. so what, a repo for each plugin + a wrapper for each game? Like it is now?

**Comment by Strikingwolf** [comment]
As an outside observer I agree with @Victorious3, @RX14, and @gjgfuj. Once you get more than one wrapper then this will fail unless you split up plugins and make core as small as possible

**Comment by gjgfuj** [comment]
And what do we do with plugin's wrappers? do we include /those/ with a plugin's repo, with the wrapper's repo, or in a plugin wrapper repo(eh.)?

**Comment by Strikingwolf** [comment]
I propose that you have a for
* Core
* Core wrappers
* Plugin
* Plugin wrapper
My reasoning is that there may be a problem for Terasology's gui wrapper, but not in mc's gui wrapper. Thus having the plugin + wrappers would make it where problems in one section of code would be reported in a much larger section of code dealing with completely different games.

**Comment by RX14** [comment]
I think that each plugin's wrappers should be split into their own repos once they reach a certain size. Once it feels too large to manage, split it. Unless of course this is a special  plugin like the minecraft plugin where it makes sense for the plugin and the wrapper to be the same codebase. 

And about 1 class plugins, yes. They should have their own repo.

**Comment by gjgfuj** [comment]
@RX14 is probably my feelings on the matter.

**Comment by Strikingwolf** [comment]
Yes, game specific plugins should be packaged with their wrappers because it is single use.

**Comment by RX14** [comment]
I also wouldn't mind enforcing that each plugin wrapper has its own repo however small, I'm really indifferent between the two methods I have mentioned.

**Comment by Victorious3** [comment]
I would let plugins have their own repos, along with their wrapper implementations just as @calclavia mentioned. Just not with core because it becomes unmanageable.

**Comment by gjgfuj** [comment]
If core is unmanageable here, then plugins would also be pretty unmanageable.

**Comment by RX14** [comment]
@Victorious3 I can see some plugins becoming larger and more diverse codebases than the core to be honest.

**Comment by Victorious3** [comment]
@gjgfuj Plugins are considerably smaller.

**Comment by Victorious3** [comment]
@RX14 Nope.

**Comment by RX14** [comment]
@Victorious3 yes. If we follow what @gjgfuj and me prefer: core is tiny and only the things that are common to every game (core utils and items/blocks)

**Comment by Victorious3** [comment]
@RX14 Its impossible. Do you know what an engine is? Its going to be huge, no matter what.

**Comment by RX14** [comment]
As in, every core module is not optional and will be moved out of core if it cannot be implemented I'm a game. If it's in core: you will always have that module.

**Comment by Victorious3** [comment]
@RX14 Stop building dream castles, its not possible. Rendering alone, including normals, everything, is a huge thing. Plugins are things that are truly optional.

**Comment by RX14** [comment]
@Victorious3 whether they are big is beside the point. Let's not engage in pointless discussion *on github*. I prefer that the plugin Dev can decide when to move wrappers out of their repo. There is no way that this can't please everyone because we give everyone the choice.

**Comment by gjgfuj** [comment]
Core should be the size of a large(ish) plugin. It should not contain things that aren't neccessary. Things that are in core at the moment that don't need to be imo:
entity
fluid
gui
inventory
recipes
sound

**Comment by RX14** [comment]
Entity? Really?

**Comment by gjgfuj** [comment]
I've played voxel games without entities.

**Comment by RX14** [comment]
Hmm, maybe that doesn't need to be in core. I had a mind derp and thought of TileEntities dammit...

**Comment by Strikingwolf** [comment]
Okay, so Nova is meant to be a modding engine for voxel games right?

What is the only thing that all voxel games have...rendered blocks...that is all a voxel is in truth (actually it is just 3d points instead of vertices for rendering, cubes is just the current style) therefore practically *everything* but blocks can be a plugin. Most standard things could be in a plugin called standard that is by default bundled with core (when downloaded by user/dev on a website), but most everything can be a plugin that is seperate

**Comment by gjgfuj** [comment]
@Strikingwolf is correct.

**Comment by gjgfuj** [comment]
Aanyway, my final opinion on the matter at the moment is that I'd like the components to be as SPLIT AS POSSIBLE.

GUI and Fluids SHOULD BE MOVED OUT.

I'd /like/ inventory, recipes, and sound to be moved out (recipes particularly).

The core, for ease of wrapping to many games, should be as lightweight as possible, so wrappers have nice, very accurate goals for completion. i.e. implement this plugin, implement that plugin.

I'd want to have a list of plugins that are best to use.

**Comment by calclavia** [comment]
I think World, Entity and Block should be kept in core. Every Voxel game needs blocks, and also entities. If there were no entities, there is no player. Entity is a broad term, and even the world camera is an entity.

Everything else that does not inter-depend on each other too much and has a significant amount of classes should move out. So I agree with GUI, Fluid, Recipes, Sound, Item Dictionary should be independent.

**Comment by Mitchellbrine** [comment]
I think GUIs, Fluids, Sound, and Item Dictionary should be moved out.

Recipes would be difficult, but it could work.

But yeah, World, Entity, Block, and Item should stay. They are vital to most games.

**Comment by gjgfuj** [comment]
GUI, Fluids, and Item Dictionary should definitely be separate. Sound has been said to be important to quite a few things, so that's that. Recipes are easy to move out I'd think, as although it's used in a lot of things, not many parts of the API would depend on it. And it'd only depend on items.

**Comment by halvors** [comment]
I think ItemDictionary should stay as that whould be a great way to identify blocks for different games.

**Comment by skyem123** [comment]
I want to note that while splitting everything out is an ideal, practicality should be considered.

**Comment by RX14** [comment]
Can we split this out later? For now we should stick with the layout of what we have because we know that it works. There's no point making massive organisational changes this often.

**Comment by RX14** [comment]
It has been noted that starting off with a monolithic architecture then splitting off modules when you are ready, after the project has momentum us less likely to fail than starting with a modular architecture. 

I suggest we stop thinking about molularusing NOVA, leave it as it is now, and return to the topic of this issue: repo format. We all agree that there will be modules, and what will be a module is another issue for another issue (if you get what I mean)

**Comment by gjgfuj** [comment]
Is that the case? If you say so. But nova is still in an early stage. It
was only recently that we switched to using a component system over
interfaces. Interfaces worked. But components are better. And more
/modular/.

**Comment by RX14** [comment]
If you want to talk about what should be a module and what shouldn't and when make a new issue, this has gotten off-topic enough.

**Comment by Kubuxu** [comment]
I agree for having core and wrappers separate but we need a simple system to reference core relatively to wrapper. It would work as:

In dev space it would use ../Nova-Core. In CI build/fallback it would use `$(git remote origin)/../Nova-Core` using selected branch or commit. With such plugin for gradle you could develop plugins/wrappers easily .

**Comment by RX14** [comment]
@Kubuxu I have plans for this, the current solution solves most if these problems (see the setup docs) but I would like to make a repo that you can check out and just develop.

I have ideas of how to do this but yet again: wait for the weekend! Then just 3 more days and I'm free.

**Comment by RX14** [comment]
I've told people to be patient so many times...

**Comment by calclavia** [comment]
Yes, let's have a full discussion in the weekend when everybody is free.

**Comment by RX14** [comment]
@calclavia `100.times { print ":+1: " }`

**Comment by Kubuxu** [comment]
I invite you for a talk on TS3 at Saturday. Address as usual but I will send it once more when I am home.

**Comment by RX14** [comment]
NovaGradle is close to ready for this to happen

**Comment by calclavia** [comment]
@RX14 Yup. We can close this once I can get a functional run config and build that works.

**Comment by calclavia** [comment]
So any decisions on this?

**Comment by calclavia** [comment]
## New Proposal
Everything in NOVA is a plugin, including NOVA-Core itself. Mods and plugins are the same thing. All plugins and repository should follow the following structure:

src/ <-- The game agnostic code
electric/src/ <-- Custom subprojects, game agnostic code
minecraft/ <-- Minecraft specific wrapper
minecraft/17/ <-- Minecraft 1.7 specific wrapper
minecraft/18/ <-- Minecraft 1.8 specific wrapper
terasology/ <-- Terasology specific wrapper
terasology/1/ <- Terasology v1 specific wrapper

This way everything can be nicely organized and build Gradle files can easily be formatted.

Suggestions?

**Comment by gjgfuj** [comment]
Well. Yeah, of course. That's good.

**Comment by RX14** [comment]
Looks good. I'm on holiday. Wait till I'm back.

**Comment by Caellian** [comment]
I agree with modular design as long as everything is accessible from one
gradle file trough tasks.

That way, a mod developer only needs to download mod template and then if
he's creating a power mod, he can just download NOVA Power Base module or
something.

Also, downloading these modules during runtime (expecially in player
environment) should be handled by NOVA.

**Comment by calclavia** [comment]
@RX14 This issue is assigned to you and due for v0.1.0 (since you're the Gradle master)

**Comment by RX14** [comment]
IM ON HOLIDAY I TOLD YOU!

**Comment by gamemanj** [comment]
@RX14 Now, now, don't try to run away from your problems~
I see you on IRC, with just /plenty/ of time to converse...
It's not very easy to hide!

**Comment by calclavia** [comment]
Note: Before closing this issue, we should write down the standard NOVA plugin restructure and put it in the README of the template, so other people who wants to build NOVA mods will know.
