### ISSUE TITLE
Make IDEs aware of values that can't ever be null

### ISSUE THREAD

**Issue by Vexatos** [NOVA-Team/NOVA-Core#91]
If there is some way of making IDEs/Compilers aware of values that cannot ever be null (Like pretty much everything in NOVA-Core), having this would be really handy because you may still do null checks out of habit etc. and the IDE would tell you if you do so. Just sticking `@NonNull` in front of every type does sound like a bad idea as it would make the code pretty messy, in my opinion. Are there any better ways of doing it?

**Comment by RX14** [comment]
An option is to write a preprocessor which marks everything as @NotNull

**Comment by RX14** [comment]
I have to basically write a java parser for the cop system in NovaGradle anyway...

**Comment by Victorious3** [comment]
@RX14 Overkill.

I don't think we have to concerned about this, stating that everything isn't null unless its Optional is enough. Even if they perform a few extra nullcheks, it won't kill anybody.

**Comment by Kubuxu** [comment]
You can annotate package as non-null.

**Comment by Kubuxu** [comment]
You can annotate package as non-null.

@RX-14 I want style point system. With positive and negative points and for what :D.

**Comment by RX14** [comment]
@Kubuxu look at rubocop, that's the model I want to emulate.
