### ISSUE TITLE
More exceptions

### ISSUE THREAD

**Issue by RX14** [NOVA-Team/NOVA-Core#92]
Replace the common `NovaException` with exceptions that subclass `NovaException` to provide  more descriptive catch code.

I suggest every NOVA exception start with `Nova`.

Exceptions  can also implement some of the logic to create the exception messages by being passed an object relevant to their throwing. This also helps to ensure they are used in the correct place.

**Comment by shadowfacts** [comment]
So you're suggesting that there be a method (e.g. `NovaException.create()`) that takes an `Object...` and then returns an instance of the correct subclass exception of `NovaException`?

**Comment by RX14** [comment]
@shadowfacts no, not at all. More like you pass it an object in the exception constructor which is used to generate the exception message.

**Comment by shadowfacts** [comment]
Ah

**Comment by RX14** [comment]
Fixed in d96904d9d8d62bcb677866769fb403856918fba6
