### ISSUE TITLE
Plugin for G/UI

### ISSUE THREAD

**Issue by Victorious3** [NOVA-Team/NOVA-Core#93]
*Taken from IRC:*
> Okay, so, the main issue that's mentioned is that core shouldn't be too specific, i.e don't contain too many code that would make writing wrappers for it complicated, which is something I couldn't disagree with.
> However, I think that G/UI is a core aspect of the game and should therefore be part of core, BUT my implementation with layouts and components certainly isn't.
So, I would replace the current system there is right now with something bare-bone, only enough to make drawing onto the screen possible and react to a few events, even less than what @calclavia suggested.
> Then I can change my system to work with that, and can, without much effort on the wrapper side because the main aspects are already managed by core, move it to a plugin

**Comment by gjgfuj** [comment]
Yep. Sounds good to me.

**Comment by calclavia** [comment]
Agreed. Your GUI is good but it's too extensive and should be placed outside as an extension of a barebones layer.

**Comment by Victorious3** [comment]
The remaining question is what is going to stay in core:
- [ ] Factory (GUI)
- [ ] Events
- [ ] Components
- [ ] Layout
- [ ] Canvas
- [ ] Graphics (Methods for drawing onto a cavas)
- [ ] Text Rendering
- [ ] Overlays
- [ ] Key input

**Comment by calclavia** [comment]
@Victorious3 Agreed.

**Comment by calclavia** [comment]
Moving UI to this repository https://github.com/NOVA-Team/NOVA-GUI

**Comment by calclavia** [comment]
Task complete
