### ISSUE TITLE
Remove the Game instance

### ISSUE THREAD

**Issue by RX14** [NOVA-Team/NOVA-Core#94]
Do we actually need the `Game` object? With DI we can inject the managers to where they are needed. This encourages the mod to make some of the modules they may depend on optional, and it does not mean you have to enumerate every manager in the `Game` object which makes modules second-class.

I think one of the best suggestions is to write our own DI system which suits exactly our needs and can be written for java 8. Any other suggestions are welcome.

**Comment by Kubuxu** [comment]
@RX14 current DI library is great. Game instance was ment to be used in items or blocks. Injecting into each item or block instance could be noticeable overhead. DI is mostly ment for mods and Game for NOVA internals.

**Comment by Victorious3** [comment]
@Kubuxu Pointing at workarounds such as: https://github.com/NOVA-Team/NOVA-Core/blob/master/src/main/java/nova/core/di/OptionalModule.java and annotations are easier to use than constructors.

**Comment by RX14** [comment]
@Kubuxu keep some manager instances in private variables on the block manager, then pass them into the block factory.

Also, if we can do annotations instead of constructors for the current DI library it would be great.

**Comment by RX14** [comment]
If the Game instance is there, then people will use it in the wrong place. And that breaks everything.

Also, writing a 20 line constructor and 8 variables for 8 modules is much worse than 8 variables and 8 annotations.

**Comment by Kubuxu** [comment]
I am against of annotations in DI. They look great and are a bit simpler but introduce next complication in discovery phase. Also it is possible with our current DI lib after writting small plugin.

Writting new lib from the ground. Nope. It is hell of fight with generics.

@Vic this is not a workaround. It is feature implementation. Optional dependency does not exist in school book DI.

**Comment by RX14** [comment]
We still need to find a way to get rid of the Game instance. I suggest making them available to block factories.

**Comment by Victorious3** [comment]
@Kubuxu I would call this a workaround. Also, Discovering constructors is the same reflective effort as iterating a few variables. I already wrote most of what's needed for more complicated reflection.

**Comment by Kubuxu** [comment]
@RX14 then move it to nova.internal. If someone touches stuff in nova.internal from outside of nova then he is asking for trouble.

Game was created as workaround so we don't have to store static state everywhere (static state makes things unbeatable)

**Comment by RX14** [comment]
Another option is to make games use their own static variables storing managers in their class. This avoids the problems of the Game class while allowing access. They already have to store the managers in variables inside the instance anyway...

**Comment by Kubuxu** [comment]
@Vic skim through source of silk. 80% is fight to make generic discovery work at runtime, remember type-erasure.

**Comment by Kubuxu** [comment]
Game should be just hidden from modders. Removing it creates many other problems.

**Comment by RX14** [comment]
We can do that, I would be happy.

**Comment by Victorious3** [comment]
@Kubuxu I wouldn't support generics at all, what do you need them for? I don't think we are making any use of it right now.

**Comment by Kubuxu** [comment]
Optional?

**Comment by Victorious3** [comment]
@Kubuxu Different annotation. As simple as that.

**Comment by RX14** [comment]
@Victorious3 How about you or I make a thingy that injects variables using the current DI library. We then don't have to touch `Optional` generics because we can have default in the annotation.

**Comment by Victorious3** [comment]
Also, optional would ALWAYS need a default.

**Comment by RX14** [comment]
@Victorious3 the default of optional is `optional.empty()`

**Comment by Victorious3** [comment]
@RX14 It wouldn't use optional.

**Comment by RX14** [comment]
@Victorious3 we should use `Optional` for constructor-based DI and don't use it for annotation-based. With annotation based we just leave the veriable as null.

**Comment by Kubuxu** [comment]
Then you have exposed null. Optional<> is the most correct way to make something optional.

And making module for Silk that injects to annotations is matter of similar length as OptioalModule (IIRC). I will make it for you if you really want.

**Comment by Kubuxu** [comment]
When we started NOVA we said no exposed null. Don't throw it away now.

**Comment by RX14** [comment]
Well, we will at least move Game to internal and make sure that anything in internal isn't in the maven dependency mods use.

**Comment by Victorious3** [comment]
As I said, my "optional dependencies" are meant for the wrapper, if the wrapper doesn't provide it, it falls back to the core. Always a value provided. Constructors are ugly.

**Comment by Kubuxu** [comment]
And this is easy in Silk just mark it as default. OptionalModule is for deps that can but may not exist.

**Comment by RX14** [comment]
What would a default module do? This is clearly possible but I would be interested in some examples.

**Comment by calclavia** [comment]
Generic injection are required actually. Look at all our registries and how they use generics.

**Comment by RX14** [comment]
I'm sure there's caching we can do in some places. I can probably move Game today, although I am not sure.

**Comment by Kubuxu** [comment]
Let's talk about it also at Saturday. Moving Game to internal is for sure good step.

**Comment by RX14** [comment]
Fixed in 149449b3
