### ISSUE TITLE
Storable constructor argument and serialization

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Core#96]
I think we should have a better method for loading Storable, but this may be a bit hacky and uses reflection.

Have a Storable object define:
```java
public static Inventory load(Data data)
```

The problem right now is that some Storable classes have constructors, making it difficult to load from Data.

This method will be called to load a particular Storable class from data. Essentially it is like serialization in Java. It would also be nice if somehow Storable and Packets can be converted easily (converting Storable into bytebuffer).

**Comment by gjgfuj** [comment]
Is simply storing every stored variable and then loading the values back
not good enough?

**Comment by calclavia** [comment]
@gjgfuj We can't load it back when the object has a constructor.

**Comment by gjgfuj** [comment]
Impose a rule that storable objects must have an empty constructor?

**Comment by calclavia** [comment]
@gjgfuj You end up with an issue where it's instsantiated with null fields. If you implement concurrency, that may cause issues (i experienced some of that)

**Comment by Kubuxu** [comment]
Native Java serializer expects you to have no-arg ctor which gets called on de-serialization. Also allows to have special methods for de-serialization. I would go with similar scheme.
I think we could even use java's Serializable interface but with custom serializer.

**Comment by Victorious3** [comment]
Java's serialization doesn't need a no-arg constructor.

**Comment by Kubuxu** [comment]
@Victorious3 ok. We could do the same with small bit of  ASM code.
